connman: Add __USE_GNU to CFLAGS
We need to define this when on musl otherwise we end up with

gdhcp/common.h:175:8: error: redefinition of 'struct in6_pktinfo'

Signed-off-by: Khem Raj <raj.khem@gmail.com>