Fix path in travis script
Fix errors like

ERROR:  OE-core's config sanity checker detected a potential
misconfiguration.
Either fix the cause of this error or at your own risk disable the
checker (see sanity.conf).
Following is the list of potential problems / advisories:

Signed-off-by: Khem Raj <raj.khem@gmail.com>